//
// This file is automatically generated. any changes will be lost
//

require("./ember-runtime");
require("./ember-views");
require("./ember-states");
require("./ember-handlebars");


(function() {
// ==========================================================================
// Project:   Ember
// Copyright: ©2011 Strobe Inc. and contributors.
// License:   Licensed under MIT license (see license.js)
// ==========================================================================

})();

