//
// This file is automatically generated. any changes will be lost
//

require("./runtime");
require("./views");
require("./states");
require("./routing");
require("./handlebars");
require("./application");


(function() {
/**
Ember

@module ember
*/

})();

