//
// This file is automatically generated. any changes will be lost
//

require("./runtime");
require("./views");
require("./states");
require("./routing");
require("./handlebars");
require("./application");


(function() {
// ==========================================================================
// Project:   Ember
// Copyright: ©2011 Strobe Inc. and contributors.
// License:   Licensed under MIT license (see license.js)
// ==========================================================================

})();

